
spring:
  application:
    name: service2
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
server:
  port: 8081

kafka_accept_value_timePeriod: 5
kafka_accept_value_lessThan: 2
